---
- hosts: vagrant
  gather_facts: yes

  vars_files:
    - vars/main.yml
    - vars/testing.yml

  vars:
    browser: firefox
    kill_selenium: False

    selenium:
      source: http://selenium-release.storage.googleapis.com/2.45/selenium-server-standalone-2.45.0.jar
      jar: ~/selenium/selenium.jar

  pre_tasks:
    - name: Check Selenium process ID
      shell: "ps aux | grep '{{ selenium.jar | basename }}' | grep -v grep | awk '{print $2}'"
      delegate_to: localhost
      register: selenium_pid

    - include: tasks/tests.kill-selenium.yml

    - name: Register variable with reports URL
      set_fact:
        reports_url: "{{ site_url }}/{{ build_reports_dir | basename }}"

  tasks:
    - include: tasks/tests.init.yml
      when: kill_selenium or selenium_pid.stdout == ""

    - name: Run tests
      sudo: yes
      shell: "cd {{ sync_root }}/tests && ../bin/behat {{ behat_vars | default('') }}"
      ignore_errors: yes

    - name: Create Behat report
      shell: 'if [ -s {{ build_reports_dir }}/behat/index.html ]; then echo "<a href=\"{{ reports_url }}/behat/index.html\" target=\"_blank\">Behat report</a>" >> {{ artifacts_file }}; fi'

  post_tasks:
    - include: tasks/tests.kill-selenium.yml
