---
- name: Check for VBox network
  shell: ifconfig | grep -Eo '(vboxnet\d+)' | awk 'END{print}' | awk '{print $1}'
  register: vbox_network
  delegate_to: localhost

- name: Check hub IP
  shell: ifconfig {{ vbox_network.stdout }} | awk '{print $2}' | grep -E -o '([0-9]{1,3}[\\.]){3}[0-9]{1,3}'
  delegate_to: localhost
  register: hub
  when: vbox_network.stdout != ""

- fail: No VBox networks exist. Try to execute 'vagrant up'.
  when: hub is undefined or hub.stdout == "" or hub.rc != 0

- name: Install Composer packages
  sudo: yes
  shell: "cd /var/www && composer install"

- name: Create directory for Selenium
  file:
    mode: 0755
    path: "{{ selenium.jar | dirname }}"
    state: directory
  delegate_to: localhost

- name: Download Selenium server
  get_url:
    url: "{{ selenium.source }}"
    dest: "{{ selenium.jar }}"
  delegate_to: localhost

- name: Run Selenium
  shell: "java -jar {{ selenium.jar }} -hub -log /tmp/selenium-hub.log &"
  delegate_to: localhost

- name: Create behat.yml
  template:
    src: ../tests/behat.yml.j2
    dest: ../tests/behat.yml
  delegate_to: localhost
