---
# This playbook installs apache

- hosts: 127.0.0.1
  connection: local
  gather_facts: yes
  sudo: yes

  vars:
    cibox_ssl_folder: /etc/apache/ssl
    apache_vhosts:
      - servername: lvivtq.dev
        documentroot: /var/www/docroot
    apache_vhosts_ssl:
      - servername: lvivtq.dev
        documentroot: /var/www/docroot
        certificate_file: "{{ cibox_ssl_folder }}/apache.crt"
        certificate_key_file: "{{ cibox_ssl_folder }}/apache.key"

  roles:
    - { role: cibox-ssl-config }
    - { role: ansible-role-apache }
